### ISSUE TITLE
Lacking critical tag in CronJob pod template

### ISSUE THREAD

**Issue by AndresPineros** [komljen/helm-charts#8]
The pod that the cronjob creates for the eviction has no annotations.
```
jobTemplate:
    metadata:
      labels:
        app: {{ template "descheduler.name" . }}
        release: {{ .Release.Name }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      template:
        metadata:
          annotations:
            scheduler.alpha.kubernetes.io/critical-pod: "true"
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
...
...
...
```
